<link rel="stylesheet" type ="text/css" href="/css/jw.css"/>
<table>
  <tr>
    <td><a href="/idea/insert"><img class="landingicon" src="/images/lNewIdea.jpg"/></a></td>
    <td><a href="/idea/edit"><img class="landingicon" src="/images/lEditIdea.jpg"/></a></td>
  </tr>
  <tr>
    <td><a href="/auth/edit/email/<?$email?>/memberPassword/<?$memeberPassword?>"><img class="landingicon" src="/images/lMemberEdit.jpg"/></a></td>
    <td><a href="/idea/search"><img class="landingicon" src="/images/lSearch.jpg"/></a></td>
  </tr>
</table>
