<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" media="screen" href="/css/main.css"/>
<link rel="stylesheet" type ="text/css" href="/css/lightbox.css"/>
<script src="/js/site.js"></script>
<script src="http://code.jquery.com/jquery-latest.js"></script>
<title>HKU Travel | Share Your Idea</title>
</head>

<table>
  <tr>
    <td class="value"><a href="/"><img src="/images/logo.jpg" alt="site logo" id="logo"></a></td>
<!--    <td class="value"><a href="/auth/auth"><img src="/images/register.png" alt="register"></a></td>
    <td class="value"><a href="/books"><img src="/images/cart.png" alt="cart"></a></td>
    <td class="value"><a href="/books"><img src="/images/login.png" alt="login"></a></td>
    <td class="value"><a href="/auth"><img src="/images/admin.png" alt="admin"></a></td>-->
     </td>
  </tr>
</table>
